// Phase 3 verification: orthogonal connectors, branch palette colors, zoom/pan
const fs = require('fs');
const vm = require('vm');
const path = require('path');

const htmlPath = path.resolve(__dirname, '../../../public/apor-family.html');
const html = fs.readFileSync(htmlPath, 'utf8');

console.log('=== PHASE 3 VERIFICATION ===');

// ---- 1. Extract script block for VM simulation ----
const scriptBlocks = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
const lastScript = scriptBlocks[scriptBlocks.length - 1][1];

// ---- 2. Orthogonal connector verification (source inspection) ----
console.log('\n--- CRITERION 1: Orthogonal connectors (no curved path commands) ---');

// Check that renderTree only uses M and L (line-to) commands, no C/Q/S/A (curves)
// Marriage: M ... L ... (horizontal)
const marriagePaths = html.match(/M \$\{A\.x \+ BOX_W\} \$\{y\} L \$\{B\.x\} \$\{y\}/);
console.log('Marriage edge uses M+L (horizontal):', !!marriagePaths);

// Parent drop: M ... L ... (vertical)
const parentDropPaths = html.match(/M \$\{pm\} \$\{py \+ BOX_H\} L \$\{pm\} \$\{busY\}/);
console.log('Parent drop edge uses M+L (vertical):', !!parentDropPaths);

// Bus: M ... L ... (horizontal)
const busPaths = html.match(/M \$\{Math\.min\(\.\.\.mids\)\} \$\{busY\} L \$\{Math\.max\(\.\.\.mids\)\} \$\{busY\}/);
console.log('Sibling bus uses M+L (horizontal):', !!busPaths);

// Sibling drops: M ... L ... (vertical)
const siblingDropPaths = html.match(/M \$\{mx\} \$\{busY\} L \$\{mx\} \$\{pos\[k\.id\]\.y\}/);
console.log('Sibling drops use M+L (vertical):', !!siblingDropPaths);

// Verify no curved path commands in renderTree's pathEl calls
// The pathEl function generates SVG path d attributes; check that the source
// only constructs paths with M and L (no C, Q, S, A)
const curvedPathPatterns = /\b[QqCcSsAa]\s/; // Curved SVG commands
const renderTreeSection = html.substring(html.indexOf('function renderTree()'), html.indexOf('function showDetail()'));
const pathConstructions = renderTreeSection.match(/pathEl\(`[^`]*`\)/g) || [];
console.log('Path construction calls found:', pathConstructions.length);

let curvedPathsFound = false;
for (const pc of pathConstructions) {
  if (curvedPathPatterns.test(pc)) {
    curvedPathsFound = true;
    console.log('  WARNING: Curved path found in:', pc.substring(0, 80));
  }
}
console.log('No curved path commands in edge generation:', !curvedPathsFound);

// Additional check: no C/Q/S/A in the path d strings generated by renderTree
// Scan for any path construction that might use curves
const allPathDs = renderTreeSection.match(/`M [^`]+`/g) || [];
let anyCurveInD = false;
for (const d of allPathDs) {
  if (/[QqCcSsAa]/.test(d.replace(/\$\{[^}]+\}/g, ''))) {
    anyCurveInD = true;
    console.log('  Curved command in d string:', d.substring(0, 80));
  }
}
console.log('All path d strings are rectilinear:', !anyCurveInD);

const orthogonalOk = !!marriagePaths && !!parentDropPaths && !!busPaths && !!siblingDropPaths && !curvedPathsFound && !anyCurveInD;
console.log('Orthogonal connectors criterion:', orthogonalOk ? 'PASS' : 'FAIL');

// ---- 3. Branch palette colors ----
console.log('\n--- CRITERION 2: Branch palette colors ---');

const expectedPalette = {
  'apor': '#2f6df6',
  'feliciano': '#16b364',
  'pedro': '#e8a63d',
  'presbitero': '#8b5cf6',
  'lumbab': '#ef4565',
};

let paletteOk = true;
for (const [branch, color] of Object.entries(expectedPalette)) {
  const cssRegex = new RegExp(`\\.br-${branch}\\s*\\{[^}]*fill:\\s*${color.replace('#', '#?')}`);
  // More flexible: check that .br-branch { ... fill: #color ... } exists
  const classDef = html.match(new RegExp(`\\.br-${branch}\\s*\\{([^}]*)\\}`));
  if (classDef) {
    const hasColor = classDef[1].includes(color);
    console.log(`  .br-${branch}: fill=${color} present: ${hasColor}`);
    if (!hasColor) paletteOk = false;
  } else {
    console.log(`  .br-${branch}: CSS class NOT FOUND`);
    paletteOk = false;
  }
}

// Check that renderTree applies the branch class via strip element
const branchStripCode = html.includes("strip.setAttribute('class', 'br-' + m.branch.toLowerCase())");
console.log('Branch class applied to node strip:', branchStripCode);

const branchPaletteOk = paletteOk && branchStripCode;
console.log('Branch palette criterion:', branchPaletteOk ? 'PASS' : 'FAIL');

// ---- 4. Zoom clamping verification ----
console.log('\n--- CRITERION 3: Zoom clamps to [0.4, 1.6] ---');

// Source inspection: check the zoomTree function clamping logic
const zoomTreeFn = html.substring(html.indexOf('function zoomTree('), html.indexOf('function fitTree('));
const clampRegex = /Math\.min\(1\.6,\s*Math\.max\(0\.4,\s*TREE_SCALE \+ delta\)\)/;
const hasClamp = clampRegex.test(zoomTreeFn);
console.log('zoomTree has clamp [0.4, 1.6]:', hasClamp);

// Check reset case (delta === 0 goes to 1)
const resetCase = zoomTreeFn.includes('delta === 0 ? 1 :');
console.log('zoomTree reset (delta=0) sets scale to 1:', resetCase);

// Check fitTree also clamps
const fitTreeFn = html.substring(html.indexOf('function fitTree()'), html.indexOf('(function initPan()'));
const fitClamp = fitTreeFn.includes('Math.min(1.6, Math.max(0.4');
console.log('fitTree also clamps [0.4, 1.6]:', fitClamp);

const zoomOk = hasClamp && resetCase && fitClamp;
console.log('Zoom clamping criterion:', zoomOk ? 'PASS' : 'FAIL');

// ---- 5. Drag-to-pan verification ----
console.log('\n--- CRITERION 4: Drag pans the tree ---');

const initPanSection = html.substring(html.indexOf('(function initPan()'), html.indexOf('renderTree();'));
const hasPointerDown = initPanSection.includes("addEventListener('pointerdown'");
const hasPointerMove = initPanSection.includes("addEventListener('pointermove'");
const hasPointerUp = initPanSection.includes("addEventListener('pointerup'");
const hasScrollManip = initPanSection.includes('sc.scrollLeft = sl -') && initPanSection.includes('sc.scrollTop = st -');
const panningClass = initPanSection.includes("sc.classList.add('panning')");

console.log('pointerdown handler on #treeScroll:', hasPointerDown);
console.log('pointermove handler:', hasPointerMove);
console.log('pointerup handler:', hasPointerUp);
console.log('scrollLeft/scrollTop manipulation:', hasScrollManip);
console.log('panning visual class toggle:', panningClass);

const dragOk = hasPointerDown && hasPointerMove && hasPointerUp && hasScrollManip && panningClass;
console.log('Drag-to-pan criterion:', dragOk ? 'PASS' : 'FAIL');

// ---- 6. VM load simulation ----
console.log('\n--- CRITERION 5: VM load simulation (no exception, no console.error) ---');

let treeAppendCount = 0;
let treeSetAttrCount = 0;
const consoleErrors = [];

const docStub = {
  getElementById: (id) => {
    if (id === 'tree') {
      return {
        _innerHTML: '',
        _w: 0, _h: 0,
        setAttribute: (k, v) => { treeSetAttrCount++; },
        appendChild: (child) => { treeAppendCount++; },
        get innerHTML() { return this._innerHTML; },
        set innerHTML(v) { this._innerHTML = v; },
        clientWidth: 800, clientHeight: 600, style: {},
      };
    }
    if (id === 'detail') {
      return { classList: { add: () => {}, remove: () => {}, contains: () => false } };
    }
    if (id === 'treeScroll') {
      return {
        scrollLeft: 0, scrollTop: 0, clientWidth: 800, clientHeight: 600,
        addEventListener: () => {}, classList: { add: () => {}, remove: () => {} },
        setPointerCapture: () => {},
      };
    }
    return {
      setAttribute: () => {}, appendChild: () => {}, innerHTML: '', textContent: '',
      classList: { add: () => {}, remove: () => {}, contains: () => false },
      addEventListener: () => {}, reset: () => {}, disabled: false, value: '',
    };
  },
  createElementNS: (ns, tag) => ({
    setAttribute: (k, v) => {},
    appendChild: (child) => { treeAppendCount++; },
    addEventListener: () => {}, style: {}, textContent: '', querySelectorAll: () => [],
  }),
  querySelectorAll: () => [],
  querySelector: () => null,
};

const sandbox = {
  document: docStub,
  window: { addEventListener: () => {} },
  console: {
    error: (...args) => consoleErrors.push(args.join(' ')),
    log: () => {}, warn: () => {}, info: () => {},
  },
  navigator: { clipboard: { writeText: () => {} } },
  I18N: {
    en: {
      formTitle: 'Form', tabForm: 'Form', tabTree: 'Tree',
      firstName: 'First', lastName: 'Last', middleName: 'Middle', gender: 'Gender',
      gUnknown: 'Unknown', gMale: 'Male', gFemale: 'Female', gOther: 'Other',
      birthDate: 'Birth', deathDate: 'Death', ifDeceased: '(if deceased)',
      visibility: 'Visibility', vPublic: 'Public', vMembers: 'Members', vPrivate: 'Private',
      photoUrl: 'Photo', photoHint: 'Photo hint', living: 'Living', notes: 'Notes',
      saveBtn: 'Save', printBtn: 'Print', copyBtn: 'Copy', clearBtn: 'Clear',
      formNote: 'Note', treeNote: 'Note', savedOk: 'Saved', submittedOk: 'Submitted',
      submitErr: 'Error', nameRequired: 'Required', copyFirst: 'Copy first', copiedOk: 'Copied',
      parentName: 'Parents', parentHint: 'Hint', maritalStatus: 'Status',
      mSingle: 'Single', mMarried: 'Married', siblings: 'Siblings', siblingsHint: 'Hint',
      saving: 'Saving', born: 'Born', died: 'Died', genderLbl: 'Gender',
      note: 'Note', livingBadge: 'Living', deceasedBadge: 'Deceased',
      notesPlaceholder: 'Notes', filterLabel: 'Branch:', filterAll: 'All',
      filterApor: 'Apor', filterFeliciano: 'Feliciano', filterPedro: 'Pedro',
      filterPresbitero: 'Presbitero', filterLumbab: 'Lumbab',
      zoomIn: 'Zoom in', zoomOut: 'Zoom out', zoomReset: 'Reset', fitBtn: 'Fit',
      legParent: 'Parent', legSpouse: 'Spouse', legSibling: 'Sibling', centerBtn: 'Center',
      branchLbl: 'Branch', genLbl: 'Gen', spouseLbl: 'Spouse', parentsLbl: 'Parents', nickLbl: 'Nick',
    },
    tl: { formTitle: 'Form', tabForm: 'Form', tabTree: 'Tree', formSub: '', formNote: '', savedOk: '', submittedOk: '', submitErr: '', nameRequired: '', copyFirst: '', copiedOk: '', notesPlaceholder: '', filterLabel: '', filterAll: '', filterApor: '', filterFeliciano: '', filterPedro: '', filterPresbitero: '', filterLumbab: '', zoomIn: '', zoomOut: '', zoomReset: '', fitBtn: '', legParent: '', legSpouse: '', legSibling: '', centerBtn: '', branchLbl: '', genLbl: '', spouseLbl: '', parentsLbl: '', nickLbl: '', firstName: '', lastName: '', middleName: '', gender: '', gUnknown: '', gMale: '', gFemale: '', gOther: '', birthDate: '', deathDate: '', ifDeceased: '', visibility: '', vPublic: '', vMembers: '', vPrivate: '', photoUrl: '', photoHint: '', living: '', notes: '', saveBtn: '', printBtn: '', copyBtn: '', clearBtn: '', parentName: '', parentHint: '', maritalStatus: '', mSingle: '', mMarried: '', siblings: '', siblingsHint: '', saving: '', born: '', died: '', genderLbl: '', note: '', livingBadge: '', deceasedBadge: '', treeNote: '' },
    ceb: { formTitle: 'Form', tabForm: 'Form', tabTree: 'Tree', formSub: '', formNote: '', savedOk: '', submittedOk: '', submitErr: '', nameRequired: '', copyFirst: '', copiedOk: '', notesPlaceholder: '', filterLabel: '', filterAll: '', filterApor: '', filterFeliciano: '', filterPedro: '', filterPresbitero: '', filterLumbab: '', zoomIn: '', zoomOut: '', zoomReset: '', fitBtn: '', legParent: '', legSpouse: '', legSibling: '', centerBtn: '', branchLbl: '', genLbl: '', spouseLbl: '', parentsLbl: '', nickLbl: '', firstName: '', lastName: '', middleName: '', gender: '', gUnknown: '', gMale: '', gFemale: '', gOther: '', birthDate: '', deathDate: '', ifDeceased: '', visibility: '', vPublic: '', vMembers: '', vPrivate: '', photoUrl: '', photoHint: '', living: '', notes: '', saveBtn: '', printBtn: '', copyBtn: '', clearBtn: '', parentName: '', parentHint: '', maritalStatus: '', mSingle: '', mMarried: '', siblings: '', siblingsHint: '', saving: '', born: '', died: '', genderLbl: '', note: '', livingBadge: '', deceasedBadge: '', treeNote: '' },
  },
  CUR: 'en',
  fetch: async () => ({ ok: true }),
  requestAnimationFrame: () => {},
};

let vmException = null;
try {
  vm.createContext(sandbox);
  vm.runInContext(lastScript, sandbox, { timeout: 10000 });
  console.log('VM execution: NO thrown exception');
} catch (e) {
  vmException = e;
  console.log('VM execution: EXCEPTION -', e.message);
}

console.log('Console errors:', consoleErrors.length > 0 ? consoleErrors : 'NONE');
console.log('SVG elements created (appendChild calls):', treeAppendCount);

const vmOk = !vmException && consoleErrors.length === 0;
console.log('VM load simulation criterion:', vmOk ? 'PASS' : 'FAIL');

// ---- 7. Edge path rectilinearity from VM output ----
console.log('\n--- CRITERION 6: Edge paths are rectilinear ---');

// Count edge paths created (by inspecting the rendered SVG)
// In the VM, the pathEl function creates path elements.
// We verify via source that all edge d-strings use only M and L commands.
// We already checked this in Criterion 1, but let's also verify by examining
// the actual path generation logic more carefully.

// Count distinct edge types
const marriageCount = (html.match(/edge marriage/g) || []).length;
const parentEdgeCount = (html.match(/edge parent/g) || []).length;
const busEdgeCount = (html.match(/edge bus/g) || []).length;
console.log('Edge class assignments in source: marriage=' + marriageCount + ', parent=' + parentEdgeCount + ', bus=' + busEdgeCount);

// Verify that all 5 branch colors appear in MEMBERS data
const memberMatch = html.match(/const MEMBERS = (\[[\s\S]*?\]);/);
let members;
try {
  members = eval(memberMatch[1]);
} catch (e) {
  console.error('FAIL: Could not parse MEMBERS:', e.message);
  process.exit(1);
}

const branchSet = new Set(members.map(m => m.branch));
console.log('Branches in data:', [...branchSet].sort().join(', '));
const allBranchesPresent = ['Apor', 'Feliciano', 'Pedro', 'Presbitero', 'Lumbab'].every(b => branchSet.has(b));
console.log('All 5 branches present in data:', allBranchesPresent);

const branchCounts = {};
members.forEach(m => { branchCounts[m.branch] = (branchCounts[m.branch] || 0) + 1; });
console.log('Members per branch:', branchCounts);

// ---- 8. Zoom extreme test (standalone computation) ----
console.log('\n--- CRITERION 7: Zoom extremes (0.4 and 1.6) ---');

// Simulate zoomTree behavior
let TREE_SCALE = 1;

function simulateZoomTree(delta) {
  const next = delta === 0 ? 1 : Math.min(1.6, Math.max(0.4, TREE_SCALE + delta));
  TREE_SCALE = next;
  return TREE_SCALE;
}

// Test zoom in to max
TREE_SCALE = 1;
for (let i = 0; i < 20; i++) simulateZoomTree(0.1);
console.log('After 20 zoom-ins from 1.0:', TREE_SCALE, '(expected 1.6)');
const zoomInMax = TREE_SCALE === 1.6;

// Test zoom out to min
TREE_SCALE = 1;
for (let i = 0; i < 20; i++) simulateZoomTree(-0.1);
console.log('After 20 zoom-outs from 1.0:', TREE_SCALE, '(expected 0.4)');
const zoomOutMin = TREE_SCALE === 0.4;

// Test reset
TREE_SCALE = 1.5;
simulateZoomTree(0);
console.log('After reset from 1.5:', TREE_SCALE, '(expected 1)');
const zoomReset = TREE_SCALE === 1;

// Test boundary
TREE_SCALE = 0.4;
simulateZoomTree(-0.1);
console.log('Zoom out from 0.4:', TREE_SCALE, '(expected 0.4, clamped)');
const boundaryClamp = TREE_SCALE === 0.4;

TREE_SCALE = 1.6;
simulateZoomTree(0.1);
console.log('Zoom in from 1.6:', TREE_SCALE, '(expected 1.6, clamped)');
const boundaryClamp2 = TREE_SCALE === 1.6;

const zoomExtremesOk = zoomInMax && zoomOutMin && zoomReset && boundaryClamp && boundaryClamp2;
console.log('Zoom extremes criterion:', zoomExtremesOk ? 'PASS' : 'FAIL');

// ---- VERDICT ----
console.log('\n========== VERDICT ==========');
const pass = orthogonalOk && branchPaletteOk && zoomOk && dragOk && vmOk && allBranchesPresent && zoomExtremesOk;
if (pass) {
  console.log('PASS');
} else {
  console.log('FAIL');
  if (!orthogonalOk) console.log('  - Orthogonal connectors not verified');
  if (!branchPaletteOk) console.log('  - Branch palette colors not verified');
  if (!zoomOk) console.log('  - Zoom clamping not verified');
  if (!dragOk) console.log('  - Drag-to-pan not verified');
  if (!vmOk) console.log('  - VM simulation failed');
  if (!allBranchesPresent) console.log('  - Not all 5 branches present in data');
  if (!zoomExtremesOk) console.log('  - Zoom extremes test failed');
}
