const { initializeApp } = require("firebase/app");
const { getFirestore, collection, doc, setDoc } = require("firebase/firestore");

const firebaseConfig = {
  apiKey: "AIzaSyA22I2BYO7VKjUnYUxV9QyOtWAsPWzw2vc",
  authDomain: "apor-tree.firebaseapp.com",
  projectId: "apor-tree",
  storageBucket: "apor-tree.firebasestorage.app",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

/**
 * Family tree data parsed from ROOTS.MD
 * Structure:
 *  Gen 0: Gerbacio Apor + Marciana Apor (roots)
 *  Gen 1: Their 6 children — Panfilo, Feliciano, Pedro, Pablo, Purificasion,
 *         Consorcia — and the spouses who married in
 *  Gen 2: Children of the Gen 1 couples
 *  Gen 3: Grandchildren (deepest generation named in ROOTS.MD)
 *
 * Married-in spouses carry parentIds: [] — only blood descendants point at parents.
 */
const members = [
  // ===================== GEN 0 — ROOTS =====================
  {
    id: "gerbacio-apor",
    fullName: "Gerbacio Apor",
    nickname: "Lolo Gerbacio",
    generation: 0,
    branch: "Apor",
    parentIds: [],
    spouseId: "marciana-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "deceased",
    notes: "Family patriarch. Root of the Apor family.",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "marciana-apor",
    fullName: "Marciana Apor",
    nickname: "Lola Marciana",
    generation: 0,
    branch: "Apor",
    parentIds: [],
    spouseId: "gerbacio-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "deceased",
    notes: "Family matriarch. Root of the Apor family.",
    sex: "female",
    maritalStatus: "married",
  },

  // ===================== GEN 1 — The six Apor siblings & spouses =====================
  {
    id: "panfilo-apor",
    fullName: "Panfilo Apor",
    nickname: "Lolo Panfilo",
    generation: 1,
    branch: "Apor",
    parentIds: ["gerbacio-apor", "marciana-apor"],
    spouseId: "antonia-montecalvo",
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "deceased",
    notes: "Eldest of the six Apor siblings. Married to Antonia Montecalvo.",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "antonia-montecalvo",
    fullName: "Antonia Montecalvo",
    nickname: "Lola Antonia",
    generation: 1,
    branch: "Apor",
    parentIds: [],
    spouseId: "panfilo-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "deceased",
    notes: "Married to Panfilo Apor.",
    sex: "female",
    maritalStatus: "married",
  },

  // ===================== GEN 2 — Children of Panfilo & Antonia =====================
  {
    id: "ricardenel-apor",
    fullName: "Ricardenel Apor",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: ["panfilo-apor", "antonia-montecalvo"],
    spouseId: "rose-ursal",
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "rose-ursal",
    fullName: "Rose Ursal",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: [],
    spouseId: "ricardenel-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "charlita-apor",
    fullName: "Charlita Apor",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: ["panfilo-apor", "antonia-montecalvo"],
    spouseId: "eliseo-arnado",
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "eliseo-arnado",
    fullName: "Eliseo Arnado",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: [],
    spouseId: "charlita-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "merlyn-apor",
    fullName: "Merlyn Apor",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: ["panfilo-apor", "antonia-montecalvo"],
    spouseId: "persing-mauro",
    birthOrder: 3,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "persing-mauro",
    fullName: "Persing Mauro",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: [],
    spouseId: "merlyn-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "yelbe-apor",
    fullName: "Yelbe Apor",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: ["panfilo-apor", "antonia-montecalvo"],
    spouseId: "reco-sevilleno",
    birthOrder: 4,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "reco-sevilleno",
    fullName: "Reco Sevilleno",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: [],
    spouseId: "yelbe-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "lonifredo-apor",
    fullName: "Lonifredo Apor",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: ["panfilo-apor", "antonia-montecalvo"],
    spouseId: null,
    birthOrder: 5,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "marlibeth-apor",
    fullName: "Marlibeth Apor",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: ["panfilo-apor", "antonia-montecalvo"],
    spouseId: "alvin-bracero",
    birthOrder: 6,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "alvin-bracero",
    fullName: "Alvin Bracero",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: [],
    spouseId: "marlibeth-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "demelito-apor",
    fullName: "Demelito Apor",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: ["panfilo-apor", "antonia-montecalvo"],
    spouseId: "reina-bajo",
    birthOrder: 7,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "reina-bajo",
    fullName: "Reina Bajo",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: [],
    spouseId: "demelito-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "jofersel-apor",
    fullName: "Jofersel Apor",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: ["panfilo-apor", "antonia-montecalvo"],
    spouseId: "rhea-boromeo",
    birthOrder: 8,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "rhea-boromeo",
    fullName: "Rhea Boromeo",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: [],
    spouseId: "jofersel-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },

  // ===================== GEN 1 — Feliciano & Flora family =====================
  {
    id: "feliciano",
    fullName: "Feliciano Apor",
    nickname: "",
    generation: 1,
    branch: "Feliciano",
    parentIds: ["gerbacio-apor", "marciana-apor"],
    spouseId: "flora",
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "living",
    notes: "Sibling branch of the Apor family.",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "flora",
    fullName: "Flora",
    nickname: "",
    generation: 1,
    branch: "Feliciano",
    parentIds: [],
    spouseId: "feliciano",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "bienvenido",
    fullName: "Bienvenido",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: ["feliciano", "flora"],
    spouseId: "narcisa",
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "narcisa",
    fullName: "Narcisa",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: [],
    spouseId: "bienvenido",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "willy-f",
    fullName: "Willy",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: ["feliciano", "flora"],
    spouseId: "marciana",
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "marciana",
    fullName: "Marciana",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: [],
    spouseId: "willy-f",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "alfredo",
    fullName: "Alfredo",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: ["feliciano", "flora"],
    spouseId: "nena",
    birthOrder: 3,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "nena",
    fullName: "Nena",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: [],
    spouseId: "alfredo",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "alberto",
    fullName: "Alberto",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: ["feliciano", "flora"],
    spouseId: "dionesia",
    birthOrder: 4,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "dionesia",
    fullName: "Dionesia",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: [],
    spouseId: "alberto",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "rodulfo",
    fullName: "Rodulfo",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: ["feliciano", "flora"],
    spouseId: "merlina",
    birthOrder: 5,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "merlina",
    fullName: "Merlina",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: [],
    spouseId: "rodulfo",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "vivina",
    fullName: "Vivina",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: ["feliciano", "flora"],
    spouseId: "teofilo",
    birthOrder: 6,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "teofilo",
    fullName: "Teofilo",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: [],
    spouseId: "vivina",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "feliciano-jr",
    fullName: "Feliciano Jr.",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: ["feliciano", "flora"],
    spouseId: "nelsa",
    birthOrder: 7,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "nelsa",
    fullName: "Nelsa",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: [],
    spouseId: "feliciano-jr",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "helenia",
    fullName: "Helenia",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: ["feliciano", "flora"],
    spouseId: "antonio-h",
    birthOrder: 8,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "antonio-h",
    fullName: "Antonio",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: [],
    spouseId: "helenia",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "merlinda",
    fullName: "Merlinda",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: ["feliciano", "flora"],
    spouseId: "elicio",
    birthOrder: 9,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "elicio",
    fullName: "Elicio",
    nickname: "",
    generation: 2,
    branch: "Feliciano",
    parentIds: [],
    spouseId: "merlinda",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },

  // ===================== GEN 1 — Pedro & Mercedes Lumbab family =====================
  {
    id: "pedro-lumbab",
    fullName: "Pedro Apor",
    nickname: "",
    generation: 1,
    branch: "Pedro",
    parentIds: ["gerbacio-apor", "marciana-apor"],
    spouseId: "mercedes-lumbab",
    birthOrder: 3,
    photoUrl: null,
    livingStatus: "living",
    notes: "Sibling branch of the Apor family.",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "mercedes-lumbab",
    fullName: "Mercedes Lumbab",
    nickname: "",
    generation: 1,
    branch: "Pedro",
    parentIds: [],
    spouseId: "pedro-lumbab",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "edita",
    fullName: "Edita",
    nickname: "",
    generation: 2,
    branch: "Pedro",
    parentIds: ["pedro-lumbab", "mercedes-lumbab"],
    spouseId: "gregorio-cole",
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "gregorio-cole",
    fullName: "Gregorio Cole",
    nickname: "",
    generation: 2,
    branch: "Pedro",
    parentIds: [],
    spouseId: "edita",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "geminda",
    fullName: "Geminda",
    nickname: "",
    generation: 2,
    branch: "Pedro",
    parentIds: ["pedro-lumbab", "mercedes-lumbab"],
    spouseId: null,
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "deceased",
    notes: "Deceased.",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "amelita",
    fullName: "Amelita",
    nickname: "",
    generation: 2,
    branch: "Pedro",
    parentIds: ["pedro-lumbab", "mercedes-lumbab"],
    spouseId: null,
    birthOrder: 3,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "venerando",
    fullName: "Venerando",
    nickname: "",
    generation: 2,
    branch: "Pedro",
    parentIds: ["pedro-lumbab", "mercedes-lumbab"],
    spouseId: null,
    birthOrder: 4,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "maridel",
    fullName: "Maridel",
    nickname: "",
    generation: 2,
    branch: "Pedro",
    parentIds: ["pedro-lumbab", "mercedes-lumbab"],
    spouseId: null,
    birthOrder: 5,
    photoUrl: null,
    livingStatus: "deceased",
    notes: "Deceased.",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "pedro-jr",
    fullName: "Pedro Jr.",
    nickname: "",
    generation: 2,
    branch: "Pedro",
    parentIds: ["pedro-lumbab", "mercedes-lumbab"],
    spouseId: null,
    birthOrder: 6,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "marites",
    fullName: "Marites",
    nickname: "",
    generation: 2,
    branch: "Pedro",
    parentIds: ["pedro-lumbab", "mercedes-lumbab"],
    spouseId: null,
    birthOrder: 7,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "luchie",
    fullName: "Luchie",
    nickname: "",
    generation: 2,
    branch: "Pedro",
    parentIds: ["pedro-lumbab", "mercedes-lumbab"],
    spouseId: null,
    birthOrder: 8,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "arnel",
    fullName: "Arnel",
    nickname: "",
    generation: 2,
    branch: "Pedro",
    parentIds: ["pedro-lumbab", "mercedes-lumbab"],
    spouseId: null,
    birthOrder: 9,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },

  // ===================== GEN 1 — Pablo & Victoriana Apor family =====================
  {
    id: "pablo-apor",
    fullName: "Pablo Apor",
    nickname: "",
    generation: 1,
    branch: "Apor",
    parentIds: ["gerbacio-apor", "marciana-apor"],
    spouseId: "victoriana-apor",
    birthOrder: 4,
    photoUrl: null,
    livingStatus: "living",
    notes: "Sibling of Panfilo Apor.",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "victoriana-apor",
    fullName: "Victoriana Apor",
    nickname: "",
    generation: 1,
    branch: "Apor",
    parentIds: [],
    spouseId: "pablo-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "rosalio-apor",
    fullName: "Rosalio Apor",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: ["pablo-apor", "victoriana-apor"],
    spouseId: "cleopatra-arnejo",
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "cleopatra-arnejo",
    fullName: "Cleopatra Arnejo",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: [],
    spouseId: "rosalio-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "leo-apor",
    fullName: "Leo Apor",
    nickname: "",
    generation: 3,
    branch: "Apor",
    parentIds: ["rosalio-apor", "cleopatra-arnejo"],
    spouseId: null,
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "lito-apor",
    fullName: "Lito Apor",
    nickname: "",
    generation: 3,
    branch: "Apor",
    parentIds: ["rosalio-apor", "cleopatra-arnejo"],
    spouseId: null,
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "cleofe-apor",
    fullName: "Cleofe Apor",
    nickname: "",
    generation: 3,
    branch: "Apor",
    parentIds: ["rosalio-apor", "cleopatra-arnejo"],
    spouseId: null,
    birthOrder: 3,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "ethel-apor",
    fullName: "Ethel Apor",
    nickname: "",
    generation: 3,
    branch: "Apor",
    parentIds: ["rosalio-apor", "cleopatra-arnejo"],
    spouseId: null,
    birthOrder: 4,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "benjie-apor",
    fullName: "Benjie Apor",
    nickname: "",
    generation: 3,
    branch: "Apor",
    parentIds: ["rosalio-apor", "cleopatra-arnejo"],
    spouseId: null,
    birthOrder: 5,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "ida-apor",
    fullName: "Ida Apor",
    nickname: "",
    generation: 3,
    branch: "Apor",
    parentIds: ["rosalio-apor", "cleopatra-arnejo"],
    spouseId: null,
    birthOrder: 6,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "roselo-apor",
    fullName: "Roselo Apor",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: ["pablo-apor", "victoriana-apor"],
    spouseId: "martiniana-ruelo",
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "martiniana-ruelo",
    fullName: "Martiniana Ruelo",
    nickname: "",
    generation: 2,
    branch: "Apor",
    parentIds: [],
    spouseId: "roselo-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "marvin-apor",
    fullName: "Marvin Apor",
    nickname: "",
    generation: 3,
    branch: "Apor",
    parentIds: ["roselo-apor", "martiniana-ruelo"],
    spouseId: null,
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "rosemarie-apor",
    fullName: "Rosemarie Apor",
    nickname: "",
    generation: 3,
    branch: "Apor",
    parentIds: ["roselo-apor", "martiniana-ruelo"],
    spouseId: null,
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "ruth-apor",
    fullName: "Ruth Apor",
    nickname: "",
    generation: 3,
    branch: "Apor",
    parentIds: ["roselo-apor", "martiniana-ruelo"],
    spouseId: null,
    birthOrder: 3,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "single",
  },

  // ===================== GEN 1 — Purificasion Apor & Eutiquio Presbitero family =====================
  {
    id: "purificasion-apor",
    fullName: "Purificasion Apor",
    nickname: "",
    generation: 1,
    branch: "Presbitero",
    parentIds: ["gerbacio-apor", "marciana-apor"],
    spouseId: "eutiquio-presbitero",
    birthOrder: 5,
    photoUrl: null,
    livingStatus: "living",
    notes: "Sibling of Panfilo Apor.",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "eutiquio-presbitero",
    fullName: "Eutiquio Presbitero",
    nickname: "",
    generation: 1,
    branch: "Presbitero",
    parentIds: [],
    spouseId: "purificasion-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "winefredo-presbitero",
    fullName: "Winefredo Presbitero",
    nickname: "Wenie",
    generation: 2,
    branch: "Presbitero",
    parentIds: ["purificasion-apor", "eutiquio-presbitero"],
    spouseId: "erlinda-p",
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "erlinda-p",
    fullName: "Erlinda",
    nickname: "",
    generation: 2,
    branch: "Presbitero",
    parentIds: [],
    spouseId: "winefredo-presbitero",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "elgendo-presbitero",
    fullName: "Elgendo Presbitero",
    nickname: "Angi",
    generation: 2,
    branch: "Presbitero",
    parentIds: ["purificasion-apor", "eutiquio-presbitero"],
    spouseId: "liza-p",
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "liza-p",
    fullName: "Liza",
    nickname: "",
    generation: 2,
    branch: "Presbitero",
    parentIds: [],
    spouseId: "elgendo-presbitero",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "marite-presbitero",
    fullName: "Marite Presbitero",
    nickname: "",
    generation: 2,
    branch: "Presbitero",
    parentIds: ["purificasion-apor", "eutiquio-presbitero"],
    spouseId: "cesar-comendador",
    birthOrder: 3,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "cesar-comendador",
    fullName: "Cesar Comendador",
    nickname: "",
    generation: 2,
    branch: "Presbitero",
    parentIds: [],
    spouseId: "marite-presbitero",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "linibeth-presbitero",
    fullName: "Linibeth Presbitero",
    nickname: "",
    generation: 2,
    branch: "Presbitero",
    parentIds: ["purificasion-apor", "eutiquio-presbitero"],
    spouseId: "catalino-pino",
    birthOrder: 4,
    photoUrl: null,
    livingStatus: "deceased",
    notes: "Deceased (+).",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "catalino-pino",
    fullName: "Catalino Pino",
    nickname: "",
    generation: 2,
    branch: "Presbitero",
    parentIds: [],
    spouseId: "linibeth-presbitero",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "arlene-presbitero",
    fullName: "Arlene Presbitero",
    nickname: "",
    generation: 2,
    branch: "Presbitero",
    parentIds: ["purificasion-apor", "eutiquio-presbitero"],
    spouseId: "tinoy-magliante",
    birthOrder: 5,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "tinoy-magliante",
    fullName: "Tinoy Magliante",
    nickname: "",
    generation: 2,
    branch: "Presbitero",
    parentIds: [],
    spouseId: "arlene-presbitero",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "herenito-presbitero",
    fullName: "Herenito Presbitero",
    nickname: "Ritoy",
    generation: 2,
    branch: "Presbitero",
    parentIds: ["purificasion-apor", "eutiquio-presbitero"],
    spouseId: "adela-p",
    birthOrder: 6,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "adela-p",
    fullName: "Adela",
    nickname: "",
    generation: 2,
    branch: "Presbitero",
    parentIds: [],
    spouseId: "herenito-presbitero",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "junito-presbitero",
    fullName: "Junito Presbitero",
    nickname: "",
    generation: 2,
    branch: "Presbitero",
    parentIds: ["purificasion-apor", "eutiquio-presbitero"],
    spouseId: null,
    birthOrder: 7,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "airic-presbitero",
    fullName: "Airic Presbitero",
    nickname: "",
    generation: 2,
    branch: "Presbitero",
    parentIds: ["purificasion-apor", "eutiquio-presbitero"],
    spouseId: "flor-p",
    birthOrder: 8,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "flor-p",
    fullName: "Flor",
    nickname: "",
    generation: 2,
    branch: "Presbitero",
    parentIds: [],
    spouseId: "airic-presbitero",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },

  // ===================== GEN 1 — Consorcia Apor & Basilio Lumbab family =====================
  {
    id: "consorcia-apor",
    fullName: "Consorcia Apor",
    nickname: "",
    generation: 1,
    branch: "Lumbab",
    parentIds: ["gerbacio-apor", "marciana-apor"],
    spouseId: "basilio-lumbab",
    birthOrder: 6,
    photoUrl: null,
    livingStatus: "living",
    notes: "Sibling of Panfilo Apor.",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "basilio-lumbab",
    fullName: "Basilio Lumbab",
    nickname: "",
    generation: 1,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "consorcia-apor",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "deceased",
    notes: "Deceased (+).",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "wilda-tejero",
    fullName: "Wilda Tejero",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: ["consorcia-apor", "basilio-lumbab"],
    spouseId: "abemeles-tejero",
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "abemeles-tejero",
    fullName: "Abemeles Tejero",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "wilda-tejero",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "deceased",
    notes: "Deceased (+).",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "limwil-tejero",
    fullName: "Limwil Tejero",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["wilda-tejero", "abemeles-tejero"],
    spouseId: "eva-tejero",
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "eva-tejero",
    fullName: "Eva",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "limwil-tejero",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "willy-tejero",
    fullName: "Willy Tejero",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["wilda-tejero", "abemeles-tejero"],
    spouseId: "marie-molinas",
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "marie-molinas",
    fullName: "Marie Molinas",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "willy-tejero",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "jesha-tejero",
    fullName: "Jesha Tejero",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["wilda-tejero", "abemeles-tejero"],
    spouseId: "jun-preagido",
    birthOrder: 3,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "jun-preagido",
    fullName: "Jun Preagido",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "jesha-tejero",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "apertito-lumbab",
    fullName: "Apertito Lumbab",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: ["consorcia-apor", "basilio-lumbab"],
    spouseId: "antonia-lanza",
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "deceased",
    notes: "Deceased (+).",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "antonia-lanza",
    fullName: "Antonia Lanza",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "apertito-lumbab",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "deceased",
    notes: "Deceased (+).",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "maryjane-lumbab",
    fullName: "Maryjane Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["apertito-lumbab", "antonia-lanza"],
    spouseId: "dante-montecillo",
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "dante-montecillo",
    fullName: "Dante Montecillo",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "maryjane-lumbab",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "faye-marie-lumbab",
    fullName: "Faye Marie Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["apertito-lumbab", "antonia-lanza"],
    spouseId: null,
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "living",
    notes: "Partner: James Dennison.",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "angel-ann-lumbab",
    fullName: "Angel Ann Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["apertito-lumbab", "antonia-lanza"],
    spouseId: null,
    birthOrder: 3,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "vilma-lumbab",
    fullName: "Vilma Lumbab",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: ["consorcia-apor", "basilio-lumbab"],
    spouseId: "antonio-hastia",
    birthOrder: 3,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "antonio-hastia",
    fullName: "Antonio Hastia",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "vilma-lumbab",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "mark-anthony-lumbab",
    fullName: "Mark Anthony Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["vilma-lumbab", "antonio-hastia"],
    spouseId: null,
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "Partner: Enrika Narvios.",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "karl-kenneth-lumbab",
    fullName: "Karl Kenneth Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["vilma-lumbab", "antonio-hastia"],
    spouseId: null,
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "living",
    notes: "Partner: Marichu Gabutin.",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "basilio-jr-lumbab",
    fullName: "Basilio Jr. Lumbab",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: ["consorcia-apor", "basilio-lumbab"],
    spouseId: "lydia-talandron",
    birthOrder: 4,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "lydia-talandron",
    fullName: "Lydia Talandron",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "basilio-jr-lumbab",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "haydee-lumbab",
    fullName: "Haydee Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["basilio-jr-lumbab", "lydia-talandron"],
    spouseId: null,
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "Partner: J.R. Roto.",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "junalyn-lumbab",
    fullName: "Junalyn Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["basilio-jr-lumbab", "lydia-talandron"],
    spouseId: "jan-bakkerud",
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "jan-bakkerud",
    fullName: "Jan Bakkerud",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "junalyn-lumbab",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "james-lumbab",
    fullName: "James Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["basilio-jr-lumbab", "lydia-talandron"],
    spouseId: "chrislyn-aranco",
    birthOrder: 3,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "chrislyn-aranco",
    fullName: "Chrislyn Aranco",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "james-lumbab",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "harrold-lumbab",
    fullName: "Harrold Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["basilio-jr-lumbab", "lydia-talandron"],
    spouseId: null,
    birthOrder: 4,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "christine-ann-lumbab",
    fullName: "Christine Ann Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["basilio-jr-lumbab", "lydia-talandron"],
    spouseId: null,
    birthOrder: 5,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "ruel-lumbab",
    fullName: "Ruel Lumbab",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: ["consorcia-apor", "basilio-lumbab"],
    spouseId: "linda-ygay",
    birthOrder: 5,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "linda-ygay",
    fullName: "Linda Ygay",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "ruel-lumbab",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "deceased",
    notes: "Deceased (+).",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "michael-lumbab",
    fullName: "Michael Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["ruel-lumbab", "linda-ygay"],
    spouseId: null,
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "Partner: Lyca.",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "charles-lumbab",
    fullName: "Charles Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["ruel-lumbab", "linda-ygay"],
    spouseId: null,
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "elma-lumbab",
    fullName: "Elma Lumbab",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: ["consorcia-apor", "basilio-lumbab"],
    spouseId: null,
    birthOrder: 6,
    photoUrl: null,
    livingStatus: "living",
    notes: "Partner: Robert Dela Cruz.",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "harlyn-lumbab",
    fullName: "Harlyn Nueva Millen Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["elma-lumbab"],
    spouseId: "john-mart-caparoso",
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "Adopted child of Elma. Partner: John Mart Caparoso.",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "john-mart-caparoso",
    fullName: "John Mart Caparoso",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "harlyn-lumbab",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "ida-lumbab",
    fullName: "Ida Lumbab",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: ["consorcia-apor", "basilio-lumbab"],
    spouseId: null,
    birthOrder: 7,
    photoUrl: null,
    livingStatus: "living",
    notes: "Partner: Arnel Verano.",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "khea-marie-lumbab",
    fullName: "Khea Marie Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["ida-lumbab"],
    spouseId: null,
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "single",
  },
  {
    id: "sherlie-lumbab",
    fullName: "Sherlie Lumbab",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: ["consorcia-apor", "basilio-lumbab"],
    spouseId: "romeo-surban",
    birthOrder: 8,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "romeo-surban",
    fullName: "Romeo Surban",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "sherlie-lumbab",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "jean-philip-lumbab",
    fullName: "Jean Philip Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["sherlie-lumbab", "romeo-surban"],
    spouseId: null,
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "christian-lumbab",
    fullName: "Christian Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["sherlie-lumbab", "romeo-surban"],
    spouseId: null,
    birthOrder: 2,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },
  {
    id: "wienna-lumbab",
    fullName: "Wienna Lumbab",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: ["consorcia-apor", "basilio-lumbab"],
    spouseId: "eric-spencer",
    birthOrder: 9,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "female",
    maritalStatus: "married",
  },
  {
    id: "eric-spencer",
    fullName: "Eric Spencer",
    nickname: "",
    generation: 2,
    branch: "Lumbab",
    parentIds: [],
    spouseId: "wienna-lumbab",
    birthOrder: 0,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "married",
  },
  {
    id: "eric-glenn-lumbab",
    fullName: "Eric Glenn Lumbab",
    nickname: "",
    generation: 3,
    branch: "Lumbab",
    parentIds: ["wienna-lumbab", "eric-spencer"],
    spouseId: null,
    birthOrder: 1,
    photoUrl: null,
    livingStatus: "living",
    notes: "",
    sex: "male",
    maritalStatus: "single",
  },
];

async function seed() {
  console.log(`Seeding ${members.length} family members...\n`);

  for (const member of members) {
    try {
      await setDoc(doc(db, "family_members", member.id), member);
      console.log(`  Added: ${member.fullName} (${member.id})`);
    } catch (err) {
      console.error(`  Failed: ${member.fullName} - ${err.message}`);
    }
  }

  console.log("\nDone!");
}

seed().catch(console.error);
